bar.default.background_opacity = 0.8
bar.default.border = "primary"
bar.default.border_width = 2.0
bar.default.capsule_thickness = 0.5999999903142452
bar.default.color = "primary"
bar.default.font_family = "CaskaydiaCove Nerd Font Propo"
bar.default.font_weight = 700
bar.default.margin_edge = 4
bar.default.margin_ends = 4
bar.default.padding = 10
bar.default.radius = 0
bar.default.shadow = false
bar.default.widget_spacing = 12
notification.background_opacity = 0.7999999821186066
notification.position = "top_center"
osd.background_opacity = 0.7999999821186066
osd.offset_y = 16
osd.position = "bottom_center"
shell.animation.speed = 2.0000000298023224
shell.app_icon_color = "tertiary"
shell.font_family = "ZedMono NFP"
shell.launcher.app_grid = true
shell.launcher.categories = false
shell.panel.control_center_placement = "floating"
shell.panel.control_center_position = "center"
shell.panel.session_placement = "floating"
shell.panel.wallpaper_placement = "floating"
shell.panel.wallpaper_position = "center"
shell.screen_corners.enabled = true
shell.screen_corners.size = 30
shell.shadow.alpha = 0.8
theme.builtin = "Catppuccin"
theme.community_palette = "Ayu Green"
theme.mode = "dark"
theme.source = "builtin"
theme.wallpaper_scheme = "faithful"
wallpaper.default.path = "/home/jj/Pictures/Wallpapers/3vpd1ov7brib1.png"
wallpaper.last.path = "/home/jj/Pictures/Wallpapers/3vpd1ov7brib1.png"
wallpaper.monitors.DP-1.path = "/home/jj/Pictures/Wallpapers/catppuccin_triangle.png"
wallpaper.monitors.HDMI-A-1.path = "/home/jj/Pictures/Wallpapers/3vpd1ov7brib1.png"
wallpaper.monitors.WAYLAND-1.path = "/home/jj/Pictures/Wallpapers/Saves/003_Ringed_kingfisher_flying_with_a_fish_in_Encontro_das_Águas_State_Park_Photo_by_Giles_Laurent.jpg"
wallpaper.monitors.eDP-1.path = "/home/jj/Pictures/Wallpapers/3vpd1ov7brib1.png"
widget.active_window.color = "primary"
widget.active_window.icon_size = 20.0
widget.active_window.max_length = 400
widget.active_window.min_length = 0
widget.active_window.title_scroll = "on_hover"
widget.battery.display_mode = "graphic"
widget.bluetooth.show_label = true
widget.clock.anchor = true
widget.clock.capsule = true
widget.clock.color = "on_surface"
widget.clock.font_weight = 700
widget.clock.format = "{:%H:%M - %a %d %b}"
widget.cpu.display = "text"
widget.cpu.show_label = false
widget.cpu.visualization = "none"
widget.network.show_label = false
widget.ram.display = "text"
widget.ram.visualization = "none"
widget.status.idle_color = "secondary"
widget.status.transcribing_color = "error"
widget.tray.detached_panel = true
widget.tray.drawer_columns = 1
widget.widget_2.capsule = true
widget.workspaces.color = "tertiary"
widget.workspaces.empty_color = "primary"
