[theme.templates.user.zellij]
input_path = "~/.config/noctalia/templates/zellij-theme.kdl"
output_path = "~/.config/zellij/themes/noctalia.kdl"
post_hook = "bash ~/.config/noctalia/scripts/zellij-reload.sh"

[theme.templates.user.nvim]
input_path = "~/.config/noctalia/templates/nvim-theme.lua"
output_path = "$XDG_CONFIG_HOME/nvim/lua/noctalia-theme.lua"
post_hook = "bash ~/.config/noctalia/scripts/nvim-theme-apply.sh"

# [theme.templates.user.hyprland-windowrules]
# input_path = "~/.config/noctalia/templates/hyprland-windowrules.lua"
# output_path = "~/.config/hypr/noctalia-windowrules.lua"
