-- Generated by Noctalia

local secondary = "rgb(ae9de7)"
local tertiary = "rgb(d29ee6)"

hl.window_rule({
	name = "jjserver-border",
	match = { workspace = "special:jjserver" },
	border_color = secondary .. " " .. secondary,
})
