-- Generated by Noctalia

local secondary = "rgb(995cd6)"
local tertiary = "rgb(cc66cc)"

hl.window_rule({
	name = "jjserver-border",
	match = { workspace = "special:jjserver" },
	border_color = secondary .. " " .. secondary,
})
