source = ~/.config/matugen/generated_templates/hypr-colors.conf

general {
    gaps_in = 2
    gaps_out = 4
    border_size = 0
    col.active_border = rgba(181926cc)
    col.inactive_border = rgba(494d6400)
    resize_on_border = true
    allow_tearing = true
    layout = dwindle
    gaps_workspaces = 0
    hover_icon_on_border = true
}

decoration {
    rounding = 10
    # dim_special = 0.7

    blur {
        enabled = yes
        size = 15
        passes = 4
        ignore_opacity = false
        noise = 0.1
        contrast = 2
        xray = false
        new_optimizations = true
    }
    
    shadow {
        # color = rgb(303040)
        range = 0
    }
}

layerrule = blur, waybar
layerrule = xray 1, waybar
layerrule = ignorezero, waybar

layerrule = blur, wofi
# layerrule = xray 1, wofis
layerrule = ignorezero, wofi

# layyerrule = ignorezero, wofi


animations {
    enabled = yes
    # animation = NAME, ONOFF, SPEED, CURVE [,STYLE]

    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1

    animation = global, 1, 10, default
    animation = border, 1, 5, easeOutQuint
    animation = windows, 1, 2, easeOutQuint
    animation = windowsIn, 1, 2, easeOutQuint, popin 87%
    animation = windowsOut, 1, 1, linear
    animation = windowsMove, 1, 2, quick, popin 87%
    animation = fadeIn, 1, 2, almostLinear
    animation = fadeOut, 1, 2, almostLinear
    animation = fade, 1, 2, quick
    animation = layers, 1, 2, easeOutQuint
    animation = layersIn, 1, 2, easeOutQuint, fade
    animation = layersOut, 1, 2, linear, fade
    animation = fadeLayersIn, 1, 2, almostLinear
    animation = fadeLayersOut, 1, 2, almostLinear
    animation = workspaces, 1, 2, quick, slide 
    animation = specialWorkspace, 1, 2, quick, slidevert
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    # background_color = 0xFF32323C
    disable_splash_rendering = true
}

input {
    kb_options = compose:ralt
    numlock_by_default = true

    touchpad {
        natural_scroll = true
    }
}

cursor {
    # Disable hardware cursors (workaround for NVIDIA GPU issues)
    no_hardware_cursors = true
}

gesture = 3, horizontal, workspace
gesture = 3, vertical, special, menu
