# workspace = special:scratchpad, on-created-empty:foot
# source = ./hyprland/windows.conf
windowrule = float, initialTitle:^(Network Manager)$
windowrule = size 800 600, initialTitle:^(Network Manager)$
windowrule = move 100%-804 48, initialTitle:^(Network Manager)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*
windowrulev2 = workspace special:menu,class:^(quick)$
