windowrule {
    name = net-man

    match:initial_title = Network Manager

    float = on
    size = 800 600
    move = (monitor_w-window_w-5) (42)
}

# windowrule {
#     name = ssh-border

#     match:title = ^jjserver.*
#     match:class = kitty
    
#     border_size = 2
#     rounding = 8
#     border_color  = rgba(8FF586dd) rgba(8FF586dd)
# }

windowrule {
    name = yazi-border
    
    match:title = ^Yazi.*
    match:class = kitty

    border_size = 2
    rounding = 8
    border_color  = rgba(8aadf4ff) rgba(8aadf4ff)
}

windowrule = xray on, match:workspace special:menu

windowrule {
    name = steam-games

    # Matches all Steam games (class is steam_app_<appid>)
    match:class = ^steam_app_\d+$

    # Pin to laptop screen, workspace 1
    monitor = eDP-1
    workspace = 1

    # Go fullscreen and allow tearing (requires allow_tearing = true in general)
    fullscreen = on
    immediate = on

    rounding = 0
}
