return { 'RRethy/base16-nvim',
  config = function()
    local ok, matugen = pcall(require, 'matugen')
    if ok then matugen.setup() end

    -- matugen.lua is regenerated by noctalia on every theme change, so any
    -- signal-handler code there gets overwritten. Own it here instead.
    -- Guard with a global so lazy re-running config() doesn't stack handlers.
    if not _G.__matugen_signal then
      _G.__matugen_signal = vim.uv.new_signal()
      _G.__matugen_signal:start('sigusr1', vim.schedule_wrap(function()
        package.loaded['matugen'] = nil
        local ok2, m = pcall(require, 'matugen')
        if ok2 then m.setup() end
        -- base16 sets highlights directly without firing ColorScheme, so nudge
        -- it for lualine etc., then force a terminal repaint (otherwise nvim
        -- won't visually refresh until the next keypress inside zellij).
        vim.api.nvim_exec_autocmds('ColorScheme', { modeline = false })
        vim.cmd('redraw!')
      end))
    end
  end,
}
