-- Generated by Noctalia

local secondary = "rgb({{colors.secondary.default.hex_stripped}})"
local tertiary = "rgb({{colors.tertiary.default.hex_stripped}})"

hl.window_rule({
	name = "jjserver-border",
	match = { workspace = "special:jjserver" },
	border_color = secondary .. " " .. secondary,
})
