# BEGIN_KITTY_FONTS
font_family family="CaskaydiaCove Nerd Font Mono"
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11.0

# Enable ligatures
disable_ligatures never

font_features CaskaydiaCoveNFM-Regular +liga +calt
font_features CaskaydiaCoveNFM-Bold +liga +calt
font_features CaskaydiaCoveNFM-Italic +liga +calt
font_features CaskaydiaCoveNFM-BoldItalic +liga +calt

cursor_shape beam
enable_audio_bell no
background_opacity 0.8
background_blur 0
allow_remote_control yes
confirm_os_window_close 0
window_padding_width 8 8
single_window_padding_width -1
single_window_margin_width -1
window_margin_width 0
draw_minimal_borders no
placement_strategy bottom
sync_to_monitor yes

# ============================================================================
# COLOR THEME
# ============================================================================
# To switch themes, change the include path below and save.
# Kitty will automatically reload if watch_for_config_changes is enabled.
# Available themes in ~/.config/kitty/themes/

# include themes/catppuccin-macchiato.conf


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
